[package]
name = "balanced-ternary"
description = "A library to manipulate balanced ternary values."
authors = ["SÃ©bastien GELDREICH <trehinos@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["ternary", "balanced-ternary", "base3"]
categories = ["data-structures", "mathematics", "science", "no-std"]

[dependencies]
